# Remplace par ton vrai projectKey et organization (sonarcloud.io)
sonar.projectKey=YOUR_ORG_taskflow
sonar.organization=YOUR_ORG
sonar.projectName=TaskFlow

sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
